In [1]:
import numpy as np
import pandas as pd

In [29]:
data = pd.read_csv('olist_order_items_dataset.csv')
data = data.drop_duplicates()
data1 = data.groupby('product_id')['order_item_id'].sum()
data1
Data1 = pd.DataFrame(data1)
Data1.rename(columns={'order_item_id':'sales_count'})

                                  sales_count
product_id
00066f42aeeb9f3007548bb9d3f33c38            1
00088930e925c41fd95ebfe695fd2655            1
0009406fd7479715e4bef61dd91f2462            1
000b8f95fcb9e0096488278317764d19            2
000d9be29b5207b54e86aa1b1ac54872            1
...                                       ...
fff6177642830a9a94a0f2cba5e476d1            2
fff81cc3158d2725c0655ab9ba0f712c            1
fff9553ac224cec9d15d49f5a263411f            1
fffdb2d0ec8d6a61f0a0a0db3f25b441            5
fffe9eeff12fcbd74a2f2b007dde0c58            1

[32951 rows x 1 columns]

In [30]:
data[data.product_id == 'fff6177642830a9a94a0f2cba5e476d1' ]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
80973,b81a52facd8a7b45a8227755b5578bb5,1,fff6177642830a9a94a0f2cba5e476d1,7a67c85e85bb2ce8582c35f2203ad736,2017-07-20 17:45:18,119.99,38.39
102653,e91d77b27ccd3bac6b23a34a44ae3db1,1,fff6177642830a9a94a0f2cba5e476d1,7a67c85e85bb2ce8582c35f2203ad736,2017-09-11 11:45:17,109.99,17.02

In [32]:
Data = pd.read_csv("new_products.csv")
Data

,product_id,product_category_name,product_category_name_english,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_name
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery Product 1
1,6a2fb4dd53d2cdb88e0432f1284a004c,perfumaria,perfumery,39.0,346.0,2.0,400.0,27.0,5.0,20.0,perfumery Product 2
2,0d009643171aee696f4733340bc2fdd0,perfumaria,perfumery,52.0,150.0,1.0,422.0,21.0,16.0,18.0,perfumery Product 3
3,b1eae565a61935e0011ee7682fef9dc9,perfumaria,perfumery,49.0,460.0,2.0,267.0,17.0,13.0,17.0,perfumery Product 4
4,8da90b37f0fb171b4877c124f965b1f6,perfumaria,perfumery,56.0,733.0,3.0,377.0,18.0,13.0,15.0,perfumery Product 5
...,...,...,...,...,...,...,...,...,...,...,...
32323,13b25797ad1e6d6c7cd3cbeb35f8ee7a,moveis_colchao_e_estofado,furniture_mattress_and_upholstery,44.0,348.0,1.0,18250.0,25.0,25.0,25.0,furniture_mattress_and_upholstery Product 32324
32324,dc36a7859b743d8610a2bbbaea26ece9,moveis_colchao_e_estofado,furniture_mattress_and_upholstery,29.0,2073.0,2.0,2500.0,41.0,21.0,21.0,furniture_mattress_and_upholstery Product 32325
32325,107fde0930956120d1e13dd1062fbb46,moveis_colchao_e_estofado,furniture_mattress_and_upholstery,51.0,418.0,1.0,30000.0,60.0,73.0,60.0,furniture_mattress_and_upholstery Product 32326
32326,726b4e18f00255e2e63491bcba3f60b8,moveis_colchao_e_estofado,furniture_mattress_and_upholstery,41.0,866.0,1.0,1700.0,70.0,10.0,100.0,furniture_mattress_and_upholstery Product 32327
32327,1dceebcc5f23c02ea23e16d5bedca000,cds_dvds_musicais,cds_dvds_musicals,47.0,117.0,2.0,550.0,35.0,15.0,25.0,cds_dvds_musicals Product 32328

In [33]:
df=pd.read_csv('olist_products_dataset.csv')
df.isnull().any()

product_id                    False
product_category_name          True
product_name_lenght            True
product_description_lenght     True
product_photos_qty             True
product_weight_g               True
product_length_cm              True
product_height_cm              True
product_width_cm               True
dtype: bool